export const NEXT_PUBLIC_CONNECT_API_ORIGIN =
  process.env.NEXT_PUBLIC_LIVE_ISCECONNECT_BACKEND_URL;
export const AUTH_API = process.env.NEXT_PUBLIC_LIVE_ISCEAUTH_BACKEND_URL;
export const baseUrl = process.env.NEXT_PUBLIC_API_URL;
export const URLS = {
  contact: {
    leave: "/api/contact/leave",
    recieved: "/api/contact/received",
    one: "/api/contact/one/{id}",
    delete: "/api/contact/delete/{id}",
    search: "/api/contact/search",
    recent: "/api/contact/recent",
    stats: "/api/contact/stats",
  },
  profile: {
    create: "/api/profile/create",
    profile: "/api/profile/me",
    update: "/api/profile/update",
    delete: "/api/profile/delete",
    stats: "/api/profile/stats",
  },
  social: {
    add: "/api/social/add",
    all: "/api/social/all",
    one: "/api/social/one/{id}",
    update: "/api/social/update/{id}",
    delete_one: "/api/social/delete/{id}",
    delete_all: "/api/social/all/delete",
    platform: "/api/social/platform/{platform}",
    stats: "/api/social/stats/overview",
  },
  notification: {
    create: "/api/notification/create",
    all: "/api/notification/all",
    one: "/api/notification/one/{id}",
    read_one: "/api/notification/read/{id}",
    read_all: "/api/notification/read-all",
    delete: "/api/notification/delete/{id}",
    unread: "/api/notification/unread",
    type: "/api/notification/type/{type}",
    recent: "/api/notification/recent",
    stats: "/api/notification/stats",
  },
  support: {
    submit: "/api/support-request/submit",
    all: "/api/support-request/all",
    one: "/api/support-request/one/{id}",
    update: "/api/support-request/update/{id}",
    delete: "/api/support-request/update/{id}",
    search: "/api/support-request/search",
    recent: "/api/support-request/recent",
    stats: "/api/support-request/stats",
  },
  card: {
    record: "/api/card-interactions/record",
    all: "/api/card-interactions/all",
    one: "/api/card-interactions/one/{id}",
    update: "/api/card-interactions/update/{id}",
    delete: "/api/card-interactions/delete/{id}",
    method: "/api/card-interactions/method/{method}",
    device: "/api/card-interactions/device/{deviceId}",
    recent: "/api/card-interactions/recent",
    stats: "/api/card-interactions/stats",
    date_range: "/api/card-interactions/date-range",
  },
  multi_profile: {
    all: "/api/profiles/all",
    one: "/api/profiles/one/{profileId}",
    update_one: "/api/profiles/update/{profileId}",
    delete_one: "/api/profiles/delete/{profileId}",
    restore_one: "/api/profiles/restore/{profileId}",
    set_default_one: "/api/profiles/set-default/{profileId}",
    get_default: "/api/profiles/default",
  },
  profile_contact: {
    add: "/api/profiles/{profileId}/contacts/add",
    all: "/api/profiles/{profileId}/contacts/all",
    one: "/api/profiles/{profileId}/contacts/one/{id}",
    update: "/api/profiles/{profileId}/contacts/update/{id}",
    delete: "/api/profiles/{profileId}/contacts/delete/{id}",
    restore: "/api/profiles/{profileId}/contacts/restore/{id}",
    visible: "/api/profiles/{profileId}/contacts/visibility/{id}",
    bulk_delete: "/api/profiles/{profileId}/contacts/all/delete",
    restore_all: "/api/profiles/{profileId}/contacts/all/restore",
    all_visible: "/api/profiles/{profileId}/contacts/visibility/all",
    primary: "/api/profiles/{profileId}/contacts/set-primary/{id}",
  },
  appointments: {
    add: "/api/profiles/{profileId}/appointments/add",
    create: "/device/create",
    user: "/device/user/{userId}",
    update: "/device/update/{id}",
  },
  user: {
    one: "/user/one/{id}",
  },
  device: {
    verify_token: "/device/verify-token",
    create: "/device/create",
    user: "/device/user/{userId}",
    update: "/device/update/{id}",
  },
};

export const DEVICE_TYPE = {
  CARD: "6214bdef7dbcb",
  WRISTBAND: "6214bdef6dbcb",
  STICKER: "6214bdef5dbcb",
  KEYCHAIN: "6214bdef4dbcb",
};
