/** ---------------------------------------
 * ICON MAPS
 * -----------------------------------------*/
export const ICONS: Record<string, string> = {
	// Brand/Platform icons from /svgs
	behance: '/svgs/icons8-behance.svg',
	facebook: '/svgs/icons8-facebook.svg',
	flickr: '/svgs/icons8-flickr.svg',
	github: '/svgs/icons8-github.svg',
	instagram: '/svgs/icons8-instagram.svg',
	linkedin: '/svgs/icons8-linkedin.svg',
	medium: '/svgs/icons8-medium.svg',
	pinterest: '/svgs/icons8-pinterest.svg',
	reddit: '/svgs/icons8-reddit.svg',
	stackoverflow: '/svgs/icons8-stack-overflow.svg',
	telegram: '/svgs/icons8-telegram-app.svg',
	tiktok: '/svgs/icons8-tiktok.svg',
	tumblr: '/svgs/icons8-tumblr.svg',
	vk: '/svgs/icons8-vk-circled.svg',
	wechat: '/svgs/icons8-wechat.svg',
	whatsapp: '/svgs/icons8-whatsapp.svg',
	xing: '/svgs/icons8-xing.svg',
	youtube: '/svgs/icons8-youtube.svg',

	// App-specific icons from /assets
	spotify: '/assets/logos_spotify-icon.svg',
	calendly: '/assets/Ellipse9.svg',
	file: '/assets/bi_filetype-pdf.svg',
	email: '/assets/entypo_email.svg',
	google_forms: '/assets/forms_2020q4_48dp.png',
	appointments: '/assets/calendar_5264073.png',
	bitcoin: '/assets/logos_bitcoin.svg',
	link: '/assets/336333cb08daaa72b8ac20c655e5f8de719c62f0.png',
};

/** ---------------------------------------
 * COVER PHOTO FALLBACKS
 * -----------------------------------------*/
export const COVER_PHOTOS = [
	'/images/cover-photos/wet-monstera-deliciosa-plant-leaves-garden.jpg',
	'/images/cover-photos/ceramic-cup-near-plate-with-twig.jpg',
	'/images/cover-photos/golden-texture-powder-dust-bursting-background-illustration.jpg',
	'/images/cover-photos/34da9859-2fbd-468d-b952-ab920832b4e0.jpg',
	'/images/cover-photos/dark-style-valentines-day-celebration.jpg',
	'/images/cover-photos/delicate-branch-black.jpg',
	'/images/cover-photos/idea-text-glow-dark-creative-concept-3d-rendering.jpg',
	'/images/cover-photos/top-view-desk-dark-concept-with-copy-space.jpg',
	'/images/cover-photos/two-skeleton-hands-orange-paper.jpg',
	'/images/cover-photos/view-3d-clouds-with-string.jpg',
];

/** ---------------------------------------
 * API CONFIGURATION
 * -----------------------------------------*/
// Server-side: prefer internal Docker URLs; client-side: falls back to NEXT_PUBLIC_
export const NEXT_PUBLIC_CONNECT_API_ORIGIN =
	process.env.CONNECT_API_URL || process.env.NEXT_PUBLIC_CONNECT_API_URL;
export const NEXT_PUBLIC_EVENT_API_ORIGIN =
	process.env.EVENTS_API_URL || process.env.NEXT_PUBLIC_EVENTS_API_URL;
export const AUTH_API =
	process.env.AUTH_API_URL || process.env.NEXT_PUBLIC_AUTH_API_URL;
// baseUrl removed — was dead code (never imported). Use AUTH_API or NEXT_PUBLIC_CONNECT_API_ORIGIN instead.
export const URLS = {
	contact: {
		leave: '/api/contact/leave',
	},
	profile: {
		create: '/api/profile/create',
		profile: '/api/profile/me',
		update: '/api/profile/update',
		delete: '/api/profile/delete',
		stats: '/api/profile/stats',
		public: '/api/profile/public/{deviceId}',
	},
	social: {
		add: '/api/social/add',
		all: '/api/social/all',
		one: '/api/social/one/{id}',
		update: '/api/social/update/{id}',
		delete_one: '/api/social/delete/{id}',
		delete_all: '/api/social/all/delete',
		platform: '/api/social/platform/{platform}',
		stats: '/api/social/stats/overview',
	},
	notification: {
		create: '/api/notification/create',
		all: '/api/notification/all',
		one: '/api/notification/one/{id}',
		read_one: '/api/notification/read/{id}',
		read_all: '/api/notification/read-all',
		delete: '/api/notification/delete/{id}',
		unread: '/api/notification/unread',
		type: '/api/notification/type/{type}',
		recent: '/api/notification/recent',
		stats: '/api/notification/stats',
	},
	support: {
		submit: '/api/support-request/submit',
		all: '/api/support-request/all',
		one: '/api/support-request/one/{id}',
		update: '/api/support-request/update/{id}',
		delete: '/api/support-request/update/{id}',
		search: '/api/support-request/search',
		recent: '/api/support-request/recent',
		stats: '/api/support-request/stats',
	},
	card: {
		record: '/api/card-interactions/record',
		all: '/api/card-interactions/all',
		one: '/api/card-interactions/one/{id}',
		update: '/api/card-interactions/update/{id}',
		delete: '/api/card-interactions/delete/{id}',
		method: '/api/card-interactions/method/{method}',
		device: '/api/card-interactions/device/{deviceId}',
		recent: '/api/card-interactions/recent',
		stats: '/api/card-interactions/stats',
		date_range: '/api/card-interactions/date-range',
	},
	multi_profile: {
		all: '/api/profiles/all',
		one: '/api/profiles/one/{profileId}',
		update_one: '/api/profiles/update/{profileId}',
		delete_one: '/api/profiles/delete/{profileId}',
		restore_one: '/api/profiles/restore/{profileId}',
		set_default_one: '/api/profiles/set-default/{profileId}',
		get_default: '/api/profiles/default',
		clone_a_profile: '/api/profiles/clone/{profileId}',
	},
	profile_contact: {
		add: '/api/profiles/{profileId}/contacts/add',
		all: '/api/profiles/{profileId}/contacts/all',
		one: '/api/profiles/{profileId}/contacts/one/{id}',
		update: '/api/profiles/{profileId}/contacts/update/{id}',
		delete: '/api/profiles/{profileId}/contacts/delete/{id}',
		restore: '/api/profiles/{profileId}/contacts/restore/{id}',
		visible: '/api/profiles/{profileId}/contacts/visibility/{id}',
		bulk_delete: '/api/profiles/{profileId}/contacts/all/delete',
		restore_all: '/api/profiles/{profileId}/contacts/all/restore',
		all_visible: '/api/profiles/{profileId}/contacts/visibility/all',
		primary: '/api/profiles/{profileId}/contacts/set-primary/{id}',
		recieved: '/api/profiles/{profileId}/contact/received',
		recieved_one: '/api/profiles/{profileId}/contact/one/{id}',
		delete_recieved: '/api/profiles/{profileId}/contact/delete/{id}',
		search_recieved: '/api/profiles/{profileId}/contact/search',
		recent_recieved: '/api/profiles/{profileId}/contact/recent',
		stats_recieved: '/api/profiles/{profileId}/contact/stats',
	},
	links: {
		add: '/api/profiles/{profileId}/links/add',
		all: '/api/profiles/{profileId}/links/all',
		one: '/api/profiles/{profileId}/links/one/{id}',
		update: '/api/profiles/{profileId}/links/update/{id}',
		delete: '/api/profiles/{profileId}/links/delete/{id}',
		restore: '/api/profiles/{profileId}/links/restore/{id}',
		visible: '/api/profiles/{profileId}/links/visibility/{id}',
		restore_all: '/api/profiles/{profileId}/links/all/restore',
		all_visible: '/api/profiles/{profileId}/links/visibility/all',
		reorder: '/api/profiles/{profileId}/links/reorder',
	},
	videos: {
		add: '/api/profiles/{profileId}/videos/add',
		all: '/api/profiles/{profileId}/videos/all',
		one: '/api/profiles/{profileId}/videos/one/{id}',
		update: '/api/profiles/{profileId}/videos/update/{id}',
		delete: '/api/profiles/{profileId}/videos/delete/{id}',
		restore: '/api/profiles/{profileId}/videos/restore/{id}',
		visible: '/api/profiles/{profileId}/videos/visibility/{id}',
		feature: '/api/profiles/{profileId}/videos/feature/{id}',
		featured: '/api/profiles/{profileId}/videos/featured',
		get_video_platform:
			'/api/profiles/{profileId}/videos/platform/{platform}',
		bulk_delete: '/api/profiles/{profileId}/videos/all/delete',
		restore_all: '/api/profiles/{profileId}/videos/all/restore',
		all_visible: '/api/profiles/{profileId}/videos/visibility/all',
	},
	meetings: {
		add: '/api/profiles/{profileId}/meetings/add',
		all: '/api/profiles/{profileId}/meetings/all',
		one: '/api/profiles/{profileId}/meetings/one/{id}',
		update: '/api/profiles/{profileId}/meetings/update/{id}',
		delete: '/api/profiles/{profileId}/meetings/delete/{id}',
		restore: '/api/profiles/{profileId}/meetings/restore/{id}',
		visible: '/api/profiles/{profileId}/meetings/visibility/{id}',
		default: '/api/profiles/{profileId}/meetings/default/{id}',
		get_default: '/api/profiles/{profileId}/meetings/default',
		meeting_provider:
			'/api/profiles/{profileId}/meetings/provider/{provider}',
		bulk_delete: '/api/profiles/{profileId}/meetings/all/delete',
		restore_all: '/api/profiles/{profileId}/meetings/all/restore',
		all_visible: '/api/profiles/{profileId}/meetings/visibility/all',
	},
	profile_social: {
		add: '/api/profiles/{profileId}/social/add',
		all: '/api/profiles/{profileId}/social/all',
		one: '/api/profiles/{profileId}/social/all',
		update: '/api/profiles/{profileId}/social/update/{id}',
		delete: '/api/profiles/{profileId}/social/delete/{id}',
		restore: '/api/profiles/{profileId}/social/restore/{id}',
		visible: '/api/profiles/{profileId}/social/visibility/{id}',
		bulk_delete: '/api/profiles/{profileId}/social/all/delete',
		all_visible: '/api/profiles/{profileId}/social/visibility/all',
		restore_all: '/api/profiles/{profileId}/social/all/restore',
		platform: '/api/profiles/{profileId}/social/platform/{platform}',
	},
	appointments: {
		add: '/api/profiles/{profileId}/appointments/add',
		all: '/api/profiles/{profileId}/appointments/all',
		one: '/api/profiles/{profileId}/appointments/one/{id}',
		update: '/api/profiles/{profileId}/appointments/update/{id}',
		delete: '/api/profiles/{profileId}/appointments/delete/{id}',
		restore: '/api/profiles/{profileId}/appointments/restore/{id}',
		visible: '/api/profiles/{profileId}/appointments/visibility/{id}',
		default: '/api/profiles/{profileId}/appointments/default/{id}',
		profile_default: '/api/profiles/{profileId}/appointments/default',
		bulk_delete: '/api/profiles/{profileId}/appointments/all/delete',
		bulk_restore: '/api/profiles/{profileId}/appointments/all/restore',
		all_visible: '/api/profiles/{profileId}/appointments/visibility/all',
	},
	spotify: {
		add: '/api/profiles/{profileId}/spotify/add',
		all: '/api/profiles/{profileId}/spotify/all',
		one: '/api/profiles/{profileId}/spotify/one/{id}',
		update: '/api/profiles/{profileId}/spotify/update/{id}',
		delete: '/api/profiles/{profileId}/spotify/delete/{id}',
		restore: '/api/profiles/{profileId}/spotify/restore/{id}',
		visible: '/api/profiles/{profileId}/spotify/visibility/{id}',
		type: '/api/profiles/{profileId}/spotify/type/{type}',
		bulk_delete: '/api/profiles/{profileId}/spotify/all/delete',
		bulk_restore: '/api/profiles/{profileId}/spotify/all/restore',
		bulk_visible: '/api/profiles/{profileId}/spotify/visibility/all',
	},
	files: {
		add: '/api/profiles/{profileId}/files/add',
		all: '/api/profiles/{profileId}/files/all',
		one: '/api/profiles/{profileId}/files/one/{id}',
		update: '/api/profiles/{profileId}/files/update/{id}',
		delete: '/api/profiles/{profileId}/files/delete/{id}',
		restore: '/api/profiles/{profileId}/files/restore/{id}',
		visible: '/api/profiles/{profileId}/files/visibility/{id}',
		file_type: '/api/profiles/{profileId}/files/type/{type}',
		download: '/api/profiles/{profileId}/files/download/{id}',
		permanent_delete: '/api/profiles/{profileId}/files/permanent/{id}',
		bulk_delete: '/api/profiles/{profileId}/files/all/delete',
		bulk_restore: '/api/profiles/{profileId}/files/all/restore',
		bulk_visible: '/api/profiles/{profileId}/files/visibility/all',
	},
	forms: {
		add: '/api/profiles/{profileId}/forms/add',
		all: '/api/profiles/{profileId}/forms/all',
		one: '/api/profiles/{profileId}/forms/one/{id}',
		update: '/api/profiles/{profileId}/forms/update/{id}',
		delete: '/api/profiles/{profileId}/forms/delete/{id}',
		restore: '/api/profiles/{profileId}/forms/restore/{id}',
		visible: '/api/profiles/{profileId}/forms/visibility/{id}',
		submit_one: '/api/profiles/{profileId}/forms/submissions/{id}',
		public_form: '/api/profiles/{profileId}/forms/public/{id}',
		public_submit: '/api/profiles/{profileId}/forms/submit/public/{id}',
		delete_submit:
			'/api/profiles/{profileId}/forms/submissions/delete/{submissionId}',
		create_template:
			'/api/profiles/{profileId}/forms/from-template/{templateId}',
		create_custom_template:
			'/api/profiles/{profileId}/forms/form-templates/add',
		bulk_delete: '/api/profiles/{profileId}/forms/all/delete',
		bulk_restore: '/api/profiles/{profileId}/forms/all/restore',
		bulk_visible: '/api/profiles/{profileId}/forms/visibility/all',
	},

	wallet: {
		add: '/api/profiles/{profileId}/wallets/add',
		all: '/api/profiles/{profileId}/wallets/all',
		one: '/api/profiles/{profileId}/wallets/one/{id}',
		update: '/api/profiles/{profileId}/wallets/update/{id}',
		delete: '/api/profiles/{profileId}/wallets/delete/{id}',
		restore: '/api/profiles/{profileId}/wallets/restore/{id}',
		visible: '/api/profiles/{profileId}/wallets/visibility/{id}',
		set_default: '/api/profiles/{profileId}/wallets/default/{id}',
		get_default: '/api/profiles/{profileId}/wallets/default',
		get_wallet_network:
			'/api/profiles/{profileId}/wallets/network/{network}',
		bulk_delete: '/api/profiles/{profileId}/wallets/all/delete',
		bulk_restore: '/api/profiles/{profileId}/wallets/all/restore',
		bulk_visible: '/api/profiles/{profileId}/wallets/visibility/all',
	},
	user: {
		one: '/user/one/{id}',
	},
	auth: {
		quick_register: '/auth/signupUser',
	},
	device: {
		verify_token: '/device/verify-token',
		create: '/device/create',
		user: '/device/user/{userId}',
		update: '/device/update/{id}',
	},
	events: {
		all: '/events/all',
		event_for_user: '/events/events',
		public_user_events: '/events/public/{userId}',
	},
};

export const DEVICE_TYPE = {
	CARD: '6214bdef7dbcb',
	WRISTBAND: '6214bdef6dbcb',
	STICKER: '6214bdef5dbcb',
	KEYCHAIN: '6214bdef4dbcb',
};
